spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url:  jdbc:mysql://localhost:3306/license
    druid:
      initial-size: 5
      max-active: 10
      min-idle: 5
      max-wait: 6000
      test-while-idle: true
      validation-query: "SELECT 1"
      test-on-borrow: false
      test-on-return: false
      filters: stat,slf4j
##使用配置来配置资源服务器相关配置 OAuth2ResourceServerConfiguration、ResourceServerProperties
security:
  oauth2:
    resource:
      id: licenseservice
    client:  ##配置客户端信息（客户端必须是已经注册的，对每个微服务都必须设置客户端信息）
      access-token-uri: http://localhost:8080/uaa/oauth/token
      user-authorization-uri: http://localhost:8080/uaa/oauth/authorize
      client-id: licenseservice
      client-secret: licenseservice
      grant-type: client_credentials
      scope: all
