
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

zuul:
  ignoredServices: '*'  #忽略基于服务发现的自动路由
  prefix: /api
  strip-prefix: true
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:
    authentication-service:
      path: /uaa/**
      #url: http://auth-service:5000
      serviceId: authenticationservice
      sensitiveHeaders:               #为空配置，转发所有请求头

    organization-service:
      path: /organization/**
      serviceId: organizationservice
      sensitiveHeaders:
    license-service:
      path: /licenses/**
      serviceId: licenseservice
      sensitiveHeaders:

