spring:
   application:
    name: mscloud-provider-dept-config                                       #定义暴露的服务名称

    
info:
  app.name: mscloud-provider-dept-config 
  
  
eureka: 
  client: 
    service-url:  
       defaultZone: http://eureka7001.com:7001/eureka
 

     
 
age: 10