server:
  port: 80
 
 
spring:
   application:
    name: mscloud-consumer-dept-feign                                     #定义暴露的服务名称
 
 
feign: 
  hystrix: 
    enabled: true  #开启feign服务降级支持
  
eureka:
  client:
    register-with-eureka: true
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka
      
  instance: 
    instance-id: mscloud-consumer-dept-feign                  
    prefer-ip-address: true 
    
    
hystrix: 
  command: 
    default:
      execution:
        timeout: 
          enabled: true  #设置超时时间
                          
        isolation: 
          thread: 
            timeoutInMilliseconds: 1000
            
            
    concurrency: 
       execution:
         timeout: 
           enabled: false  #设置超时时间
                          
         isolation: 
          thread: 
            timeoutInMilliseconds: 85000
            
            
    DeptFeignClientService#get(Long):  
       execution:
         timeout: 
           enabled: true  #设置超时时间
                          
         isolation: 
          thread: 
            timeoutInMilliseconds: 2000
            
            
    mscloud-provider-dept-hystrix-8001:  
       execution:
         timeout: 
           enabled: true  #设置超时时间
                          
         isolation: 
          thread: 
            timeoutInMilliseconds: 120000