spring:
  application:
    name: zuulservice
    
  profiles:
    active: dev  
      
  cloud:
    config:
      enabled: true


  #Setting logging levels
logging:
    level:
      com.netflix: WARN
      org.springframework.web: WARN
      com.thoughtmechanix: DEBUG

eureka:
  instance:
    preferIpAddress: true
    hostname: zull5555.com
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone:  http://eureka7001.com:7001/eureka


zuul:
  prefix:  /api
  strip-prefix: true
  routes:
    MSCLOUD-CONSUMER-DEPT-FEIGN: /depts/**
    ignored-services: "*"
  
  ##使用静态URL配置
    dept:   
      path: /consumer/**
      url: http://localhost 
      
     ##通过服务ID配置
    dept-consumer-feign:  #任意写
         path: /dept-consumer-feign/**
         serviceId: MSCLOUD-CONSUMER-DEPT-FEIGN

management:
  security:
    enabled: false
    
    
hystrix: 
  command: 
    default:
      execution:
        timeout: 
          enabled: true  #设置超时时间
                          
        isolation: 
          thread: 
            timeoutInMilliseconds: 100000
            
    