spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: 123456
        url:  jdbc:mysql://localhost:3306/org
        druid:
            initial-size: 5
            max-active: 10
            min-idle: 5
            max-wait: 6000
            test-while-idle: true
            validation-query: "SELECT 1"
            test-on-borrow: false
            test-on-return: false
            filters: stat,slf4j
##使用配置来配置资源服务器相关配置 OAuth2ResourceServerConfiguration、ResourceServerProperties
security:
    oauth2:
        resource:
            id: orgnazationservice
            token-info-uri: http://localhost:8080/uaa/oauth/check_token #RemoteTokenServices
            userInfoUri: http://localhost:8080/uaa/oauth/user    #对应UserInfoTokenServices
            prefer-token-info: true  #是否优先使用token-info-uri
        client:  ##配置客户端信息（客户端必须是已经注册的，对每个微服务都必须设置客户端信息）
            accessTokenUri: http://localhost:8080/uaa/oauth/token
            userAuthorizationUri: http://localhost:8080/uaa/oauth/authorize
            clientId: eagleeye
            clientSecret: thisissecret


#Setting the logging levels for the service
logging:
    level:
        com.netflix: WARN
        org.springframework.web: WARN
        com.thoughtmechanix: DEBUG