server:
  port: 3344
  
spring:
  cloud:
    config: 
      server: 
        git:
          uri: https://github.com/oldboy-java/mscloud-config.git 
  application:
    name: config-service  

eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port} # 使用IP注册，默认以机器名注册
    prefer-ip-address: true
  client: 
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://eureka7001.com:7001/eureka}

info:
  app.name: config-service
  company.name: www.tk.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$    
  
