spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url:  jdbc:mysql://localhost:3306/uaa
    druid:
      initial-size: 5
      max-active: 10
      min-idle: 5
      max-wait: 6000
      test-while-idle: true
      validation-query: "SELECT 1"
      test-on-borrow: false
      test-on-return: false
      filters: stat,slf4j

    redis:
      port: 6379
      host: localhost

mybatis-plus:
  mapper-locations:
    - classpath*:META-INF/mybatis/mapper/**/*.xml
  config-location: classpath:META-INF/mybatis/mybatis-config.xml
#Setting the logging levels for the service
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.thoughtmechanix: DEBUG
    org.springframework.security: DEBUG

