#Default port is 8761
server:
  port: 8761

eureka:
  client:
    registerWithEureka: false  #不使用Eureka服务进行注册
    fetchRegistry: false            #不要在本地缓存注册表信息
    serviceUrl: 
       defaultZone: http://localhost:8761/eureka
  server: 
    waitTimeInMsWhenSyncEmpty: 0 #在服务器接收请求之前等待的初始时间

#Setting logging levels
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.thoughtmechanix: DEBUG
